const textsToType = [
    // Train
    "The quick brown fox jumps over 123 lazy dogs five times. On January 1st, 2025, 7 zebras danced gracefully, eating 89 pizzas under 6 bright lamps. Curious owls, 4 total, observed as 3 frogs croaked near the 0 degree pond. Bees buzzed 12 times before spotting 23 flowers growing in a vibrant A to Z rainbow. Xylophones, said the quirky parrots, make a joyful sound every 5 to 9 seconds.Meanwhile, 345 sailors sang sea shanties beneath 678 twinkling stars, their voices echoing 890 chords into the vast abyss.",

    "Amid the vibrant festival on June 5th, 2024, 7 lively musicians played tunes from A to Z. Crowds cheered as 8 zebras dashed past 9 glowing lanterns, while 345 balloons floated above the scene. The quick fox jumped over 12 lazy dogs 6 times, barking loudly each time. An owl hooted 3 times as 0 frogs hopped along the muddy path, observing the scattered petals of a rainbow colored bouquet. By midnight, 89 twinkling stars illuminated the stage, and 567 partygoers sang in harmony, clapping and shouting numbers like 1, 2, 3, and 4 with unbridled joy, celebrating life to the fullest.",

    "On a crisp October evening, 5 daring adventurers set out to explore the forest, carrying maps marked from A to Z. They discovered 12 hidden caves, 8 sparkling streams, and 9 glowing fireflies that lit up the night. The quick brown fox dashed past 7 lazy squirrels, while 3 owls hooted loudly from 5 towering trees. Nearby, a group of 6 frogs leaped over 0 rocks into a pond that shimmered like silver under the moonlight. As they camped, 345 stars twinkled above, and they counted 678 fireflies circling around, marveling at the magical beauty of numbers and nature entwined.",

    "Beneath the bright evening sky, 5 young explorers gathered to count the stars, each taking turns naming constellations from A to Z. The quick brown fox leapt gracefully over 7 sleepy dogs, while 3 chirping crickets serenaded the night. In the distance, 12 owls hooted, and 6 frogs splashed in a pond reflecting 89 twinkling stars. Around the campfire, they shared stories of the 345 adventures they would dreamed of, punctuated by laughter and the sound of 0 worries in the world. By midnight, they had counted 678 glowing fireflies and marveled at how nature, like numbers, always found a way to bring magic to life.",

    "In the bustling town square, 5 jugglers performed tricks with glowing balls marked A to Z, dazzling a crowd of 345 cheering onlookers. A quick brown fox darted between 7 colorful stalls, while 6 frogs croaked melodiously by a 0 degree fountain. Nearby, 12 musicians played a lively tune, their instruments creating a symphony of sound. As the clock struck 8, 9 firecrackers lit up the sky, and 89 children clapped in delight. The energy of the night was electric, with 678 stars twinkling above and laughter echoing from all corners, celebrating the unbreakable rhythm of life, letters, and numbers.",

    "On a breezy summer afternoon, 5 adventurers trekked through a vibrant meadow, their backpacks labeled from A to Z. A quick brown fox dashed past 7 grazing deer, while 6 frogs hopped near a glimmering stream. Overhead, 9 birds circled the sky, and 12 dragonflies danced above 0 ripples in the water. Nearby, 345 flowers bloomed in radiant colors, attracting 89 buzzing bees. As dusk fell, the group gazed at 678 stars lighting up the heavens, marveling at the beauty of nature's endless patterns and the harmony between the alphabet and numbers in their journey.",

    "At dawn, 5 curious children wandered into the enchanted forest, guided by a trail marked with letters A through Z. The quick brown fox playfully darted between 7 towering trees, while 6 frogs leapt into a 0 degree crystal clear pond. Overhead, 9 sparrows chirped as they flew past 12 shimmering cobwebs glistening in the light. The adventurers counted 89 mushrooms growing in a spiral and spotted 345 fireflies blinking in rhythmic harmony. By nightfall, under a sky boasting 678 glittering stars, they shared stories, blending the magic of letters and numbers into an unforgettable tale.",

    "Under the warm glow of 678 stars, 5 travelers ventured through a lively marketplace filled with signs from A to Z. A quick brown fox darted past 7 bustling stalls selling everything from 12 jars of honey to 89 vibrant scarves. Nearby, 6 frogs croaked in harmony beside a fountain at 0 degrees, its waters sparkling in the moonlight. Children laughed as they counted 345 lanterns lighting up the square, while 9 musicians played a cheerful tune. The night buzzed with energy, a perfect blend of numbers, letters, and the boundless joy of life.",

    "dear team, i hope you all had a fanstastic time our recent employee appreciation event. it was truly a pleasure to see everyone come together and enjoy the festivities. your enthusiasm and positive energy made the event a resounding success. we wanted to take a moment to extend our heartfelt gratitude to each of your hard work and dedication. events like these are a small token of appreciation for the incredible effort you put into your roles everyday. as we move forward, lets carry forward this spirit of camaraderie and teamwork. your contributions are invaluable to our company success, and we look forward to achieveing even greater milestones together. once again, thank you for being an integral part of our team. heres to continue success and many more memorable moments ahead. best regards, katty",

    "As the sun set over the hills, 5 hikers gathered around a campfire, their backpacks embroidered with letters from A to Z. A quick brown fox darted past 7 chirping crickets and 6 frogs leaping near the 0 degree lake. Overhead, 9 bats flitted through the twilight, while 12 fireflies blinked in rhythm among the trees. The hikers shared stories of their 89 mile journey, marveling at the beauty of the 345 wildflowers blooming in the valley. Under the glow of 678 stars, they laughed and embraced the harmony of letters, numbers, and natures wonders.",

    "hello john, thank you for shopping at our website. we guarantee your satisfaction with our high quality products and customer support. since your expertise with the order did not live up to our high standards, we have issued you a credit in the amount of a hundred. please allow three to five days for your bank to apply this credit to your account. if you have any questions, please visit customer support. thank you again for shopping with us. we look forward to serving you in the future. sincerely",

    "jennifer, thanks for hosting the meeting yesterday. sorry i had to leave but i had to meet with beth pearlman. i believe there was a lot of good information exchanged and that is why we ran so late. i certainly came away with a different insight to enron that i did not have before we met. regarding the relationship between compaq and enron, i need to make some things are very clear in our go forward strategy. at the end of the day, the account team, dave spurlin up through jeff, myself, and jerry, own the responsibility for the enron relationship. if corporate folks are making deals with enron, we still have to manage the account. peter blackmore is very clear about that. he was always preserved the integrity of the account team as being responsible for the customer. that is why we need to keep dave focused and knowing what transactions are taking place withing enron. he is not the decision maker or deals like the ebs one, but as you are well aware of, the ebs contract has impaired other business opportunities within enron. daves role responsibility is enron and making sure that we have resolutions for situations that impact the relationship with enron. he is not the decision maker or deals like the ebs one, but as you are well aware of, the ebs contract has impaired other business opportunities within enron. daves role responsibility is enron and making sure that we have resolutions for situations that impact the relationship with enron. he has to ahve the total picture of business transactions happening at enron. he will understand how those situations can impact the business at and for enron.",

    "Good afternoon, The Board of Directors meetings have been scheduled as follows, January, previously confirmed, May, July, and October. Each meeting will take place from 9.00 AM to noon. Further logistical details will be announced closer to each meeting date. If you have any questions, please feel free to contact either Keith Larney or me. Thank you.",

    // Validate
    "dear ken, first off, i have a friend who is setting up a plant in corconran northern calif. to manufacture a welded reinforcement grid building structure systems. they will need vamp. service. i suggested that they would be better of making an electricity provision agreement with you rather than pg e. his name is hans bauman. he can be reached at. please have your people contact him asap as he plans to open for bussiness in november. next, the aspen accord conference in sweden went extraordinarily well... especially with the california issue in such a bound. i know that there is a business opportunity that can be developed and would be pleased, when the timing is right to discuss this with you. after all ken, your california experience should show that the improvement in position in the marketplace could be better. why not, on your next trip to aspen, give me a call and drop by orange county airport and i ll ride up with you. we can talk about what i see as lost opportunities and how to capture them. my new life is going amazingly well. im working in an advisory capacity in california. chicago and sweden.. and taking time to smell the roses. hope you are doing the same. best regards, john.",

    "On a starlit night, 5 stargazers gathered on a hill, their notebooks filled with sketches from A to Z. A quick brown fox darted across the meadow, weaving between 7 curious rabbits and 6 frogs croaking beside a 0 degree brook. Overhead, 9 shooting stars streaked through the sky as 12 owls hooted softly from nearby trees. The group marveled at 89 constellations they had mapped and the 345 glimmering lights of a distant village. Surrounded by the brilliance of 678 celestial bodies, they felt the seamless connection between the infinite letters, numbers, and the wonders of the cosmos.",

    "In 2023, 758925 scientists worked on 512355 experiments for 6515135 months, running 151808 tests daily across 166437 labs with 4900 computuers and 300 machines each processing 769310 datasets. Over 563260 prototypes were developed, 421230 errors were fixed, and 100 equations were solved. By day 35680, they reduced 9 major problems to 0, scaling the project to impact 75770 cities using 537 formulas and 9689 reactors. Thei 9632449 budget supported 10 teams across 4670 locations, benefiting 116895 homes with renewable energy in under 26356 months, while collecting over 5263632 data points.",

    "Dear Dr. Lay, I am pleased to invite you to join my CERA colleagues and me at our annual executive conference, Shooting the Rapids, Strategies and Risks for the Energy Future, to be held this February in Houston, Texas. This premier international gathering offers senior executives new ideas, insights, and strategic thinking on the challenges facing the global energy industry. The conference will focus on the implications of current market turmoil for energy strategies, investment, regulatory challenges, competitive dynamics, and industry structure, with presentations covering oil, natural gas, power, and their interconnections across key regions. As the centerpiece of CERAWeek, it also provides opportunities for informal interaction and networking, with last year event drawing executives from over 50 countries. For more details, please visit CERA.com or register at register.cera.com. I hope you will join us. Sincerely, Daniel Yergin Chairman, Cambridge Energy Research Associates",

    // Test
    "At the break of dawn, 5 adventurers set off on a trail marked by signposts labeled A to Z. A quick brown fox scurried past 7 colorful butterflies fluttering near 6 frogs basking on the edge of a 0-degree stream. In the distance, 9 deer grazed peacefully under the shade of 12 ancient oaks. The travelers paused to admire 89 wildflowers blooming in vibrant hues and counted 345 pebbles forming a natural mosaic along the path. By nightfall, under a sky glittering with 678 stars, they shared stories of discovery, marveling at the unity of natures letters and numbers.",

    "On a cool spring evening, 5 friends explored a magical garden where flowers bloomed in patterns from A to Z. A quick brown fox dashed between 7 rows of roses, while 6 frogs sang near a pond chilled to 0 degrees. Overhead, 9 swallows darted gracefully, and 12 glowing butterflies danced in the air. The group counted 89 shining crystals embedded in a nearby fountain and marveled at 345 twinkling lights strung through the trees. As the clock struck midnight, 678 stars sparkled above, casting a celestial glow over the enchanted scene",

    "In the heart of a mystical valley, 5 explorers uncovered a hidden realm where the alphabet from A to Z adorned ancient stone carvings. A quick brown fox sprinted past 7 glittering waterfalls, while 6 frogs perched on lily pads in a pond shimmering at 0 degrees. Overhead, 9 luminous birds soared, their wings reflecting the light of 12 golden orbs. Among the lush greenery, 89 blooming orchids stretched skyward, and 345 fireflies danced in perfect unison. Beneath the canopy of 678 twinkling stars, the adventurers marveled at the harmony of letters, numbers, and the magic of the universe.",

    "the five boxing wizards jump quickly,. pack my box with five dozen liquor jugs,. go lazy fat vixen be shrewed jump quickly,. when zoombies arrives, quickly fax judge pat,. amazingly few discotheques provide juke boxes,. puzzled women bequeatha jerks very exotic gifts. the quick onyx goblin jumps over the lazy dwarf. brawny gods just flocked up to quiz and vex him. watch jeopardy, alex trebeks fun tv quiz game. six big devils from japan quickly forgot how to waltz. five or six big devils from japan quickly forgot how to waltz. five or six big jet planes zoomed quickly be the tower. jack amazed a few girls by dropping the antique onyx vase. a quick movement of the enermy will jeopardize six gun boats. jaded zoombies acted quaintly but kept driving their oxen forward. no kidding lorenzo called off his trip to mexico city just because they told him the conquistador were extinct.",

    "dear quincy, i hope you are doing well. i wanted to update you on our latest project, which has been quite the journey. the work involves a series of complex tasks, each with its unique challenges. our team, including kevin and zelda, has been diligently working to tackle these issues. recently we faced several quirky situations that required immediate acttention. thankfully, we managed to address them with the help of our innovative techniques and quick adjustments. the process has been quite rigorous, but we are making significant strides. our project is driven by advanced algorithms and cutting edge technology. the key aspects include xray data analysis, zipping through extensive datasets, and precise measurements. we have had to navigate through tricky scenarios, but we are confident in the direction we are heading. if you have any questions or need more details, please feel free to reach out. we are available for a quick call if that would be more convenient. your feedback and insights are highly valued and will help us ensure the project meets all expectations. thank you for your continued support and understanding. we look forward to sharing more updates with you soon. best regards, jack q. zimmer",
]